import type { Metadata } from "next";
import "./globals.css";
import { ProfileHeader } from "@/components/ProfileHeader/ProfileHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black/20">
        <ProfileHeader />
        {children}
      </body>
    </html>
  );
}
